<a href="https://colab.research.google.com/github/amishali/Electric-car/blob/master/python_wk4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Data Cleaning and Analysis -- Autolib Dataset

Importing our Libraries

In [144]:
# Importing the libraries we will need 

# Importing the pandas library
# 
import pandas as pd

# Importing the numpy library
#
import numpy as np

Reading the Dataset from our CSV file

Dataset link for download or access:[http://bit.ly/autolib_dataset (Links to an external site.)]

viewing our dataset


In [145]:
df = pd.read_csv('Autolib_dataset (2).csv')
df.head()

Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue Eugène Oudiné     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

In [102]:
df.shape

(5000, 25)

Accessing Information about our Dataset

In [103]:
#let get to know about the datast
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64 
 2   Bluecar counter      5000 non-null   int64 
 3   Utilib counter       5000 non-null   int64 
 4   Utilib 1.4 counter   5000 non-null   int64 
 5   Charge Slots         5000 non-null   int64 
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64 
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots 

In [104]:
df.describe()

Cars  Bluecar counter  ...         hour       minute
count  5000.000000      5000.000000  ...  5000.000000  5000.000000
mean      2.333600         2.333600  ...    11.509200    29.270000
std       2.035274         2.035274  ...     6.893549    17.231741
min       0.000000         0.000000  ...     0.000000     0.000000
25%       0.000000         0.000000  ...     6.000000    14.000000
50%       2.000000         2.000000  ...    11.000000    29.000000
75%       4.000000         4.000000  ...    18.000000    44.000000
max       7.000000         7.000000  ...    23.000000    59.000000

[8 rows x 12 columns]

** Cleaning our Dataset **

Let us perform data cleaning procedures below providing a documentation for our actions. We will perform as many data cleaning procedures as we think suitable for the various dimensions of data.

validity


In [160]:
#drop irrelevant column 

df.drop(['Displayed comment'], axis = 1 , inplace = True) 
df

Address  Cars  ...  usage_utilib  usage_utilib14
0                    2 Avenue de Suffren     0  ...           NaN             NaN
1              145 Rue Raymond Losserand     6  ...           0.0             0.0
2       2 Avenue John Fitzgerald Kennedy     3  ...           0.0             2.0
3                 51 Rue Eugène Oudiné     3  ...           1.0            -2.0
4     6 avenue de la Porte de Champerret     3  ...          -1.0             0.0
...                                  ...   ...  ...           ...             ...
4995                 8 avenue Ménelotte     2  ...           0.0             0.0
4996                   37 rue de Dantzig     4  ...           0.0             0.0
4997                      142 rue du Bac     1  ...           0.0             0.0
4998         2 avenue du Val de Fontenay     2  ...           0.0             0.0
4999                 5 Rue Henry Brisson     4  ...           0.0             0.0

[5000 rows x 26 columns]

In [161]:
df.drop(["Scheduled at"], axis = 1, inplace = True) 
  
# Display the resulting dataframe
df 

KeyError: ignored

In [107]:
#checking for unique values in the hour column
df['hour'].unique()

array([11,  7, 20,  4, 17, 18, 22, 15,  9, 12, 21,  8,  0, 19,  6,  3, 23,
        2,  1, 10, 16, 13, 14,  5])

In [50]:
#checking for unique values in the month column
df['month'].unique()

array([4])

In [51]:
#checking for unique values in the year column
df['year'].unique()

array([2018])

In [52]:
#checking for unique values in the city column
df['City'].unique()

array(['Paris', 'Le Bourget', 'Nanterre', 'Puteaux', 'Fontenay-aux-Roses',
       'Le Chesnay', 'Suresnes', 'Versailles', 'Malakoff',
       'Issy-les-Moulineaux', 'Saint-Cloud', 'Sèvres', 'Bezons',
       'Nogent-sur-Marne', 'Créteil', 'Villejuif', 'Rueil-Malmaison',
       'Villeneuve-la-Garenne', 'Montreuil', 'Charenton-le-Pont',
       'Courbevoie', 'Asnières-sur-Seine', 'Garches', 'Drancy',
       'La Garenne-Colombes', 'Verrières-le-Buisson', 'Le Blanc-Mesnil',
       'Vanves', 'Enghien-les-Bains', 'Sceaux', 'Levallois-Perret',
       'Boulogne-Billancourt', 'Châtenay-Malabry', 'Pantin', 'Meudon',
       'Gennevilliers', 'Vincennes', 'Rungis', 'Colombes',
       'Fontenay-Sous-Bois', 'Rosny-sous-Bois', 'Bourg-la-Reine',
       'Cachan', 'Maisons-Alfort', 'Bièvres', 'Alfortville',
       'Champigny-sur-Marne', 'Aulnay-sous-bois', 'Saint-Denis',
       'Le Plessis-Robinson', 'Le Pré-Saint-Gervais', 'Clamart',
       'Bois-Colombes', 'Guyancourt', 'Bagnolet', 'Vaucresson',
  

In [54]:
#checking for unique values in the Public name   column
df['Public name'].unique()

array(['Paris/Suffren/2', 'Paris/Raymond Losserand/145',
       'Le Bourget/John Fitzgerald Kennedy/2', ...,
       'Paris/Vercingétorix/106', 'Nanterre/National/134',
       'Paris/Sérurier/54'], dtype=object)

In [55]:
#checking for unique values in the day column
df['day'].unique()

array([8, 6, 3, 4, 2, 1, 5, 9, 7])

In [56]:
#checking for unique values in the address column
df['Address'].unique()

array(['2 Avenue de Suffren', '145 Rue Raymond Losserand',
       '2 Avenue John Fitzgerald Kennedy', ..., '106 rue Vercingétorix',
       '134 boulevard National', '54 Boulevard Sérurier'], dtype=object)

In [57]:
#checking for unique values in the Bluecar counter column
df['Bluecar counter'].unique()

array([0, 6, 3, 1, 5, 4, 2, 7])

In [108]:
#since the column year and month are same and don't have unique value we can drop them
df.drop(['year'	,'month'], axis = 1, inplace = True) 
  
# Display the resulting dataframe
df

Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue Eugène Oudiné     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue Ménelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 21 columns]

completeness

In [109]:
#Checking/ Counting Missing Values 
# Checking if there is any missing value across each column
df.isnull().any()

# Checking how many missing values there are across each column
df.isnull().sum()


Address                0
Cars                   0
Bluecar counter        0
Utilib counter         0
Utilib 1.4 counter     0
Charge Slots           0
Charging Status        0
City                   0
ID                     0
Kind                   0
Geo point              0
Postal code            0
Public name            0
Rental status          0
Slots                  0
Station type           0
Status                 0
Subscription status    0
day                    0
hour                   0
minute                 0
dtype: int64

In [75]:
#checking the not null column
df.notnull().sum()

Address                5000
Cars                   5000
Bluecar counter        5000
Utilib counter         5000
Utilib 1.4 counter     5000
Charge Slots           5000
Charging Status        5000
City                   5000
ID                     5000
Kind                   5000
Geo point              5000
Postal code            5000
Public name            5000
Rental status          5000
Slots                  5000
Station type           5000
Status                 5000
Subscription status    5000
day                    5000
hour                   5000
minute                 5000
dtype: int64

In [110]:
# Droppping all missing value

clean_df = df.dropna()
clean_df

# Verifying that you no longer have any null values 
#clean_df.isnull().sum()

Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue Eugène Oudiné     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue Ménelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 21 columns]

In [ ]:
clean_df.shape

(47, 24)

 Consistency

In [111]:
# Identifying which observations are duplicates
df3 = df.drop_duplicates()

# Let's see these non-duplicate files
df3

Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue Eugène Oudiné     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue Ménelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 21 columns]

Uniformity

In [164]:

# Rename the columns for uniformity
df = df.rename(columns={"Bluecar counter": 'bluecar_counter',
                        "Utilib counter": 'utilib_counter',
                        "Utilib 1.4 counter": 'utilib_14_counter',
                        "Rental status": 'rental_status',
                         "Charge Slots" : 'charging_slots' ,       
                         "Station type"   : 'station_type'})


In [163]:
#fixing messy column name
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
df.columns

Index(['address', 'cars', 'bluecar_counter', 'utilib_counter',
       'utilib_14_counter', 'charging_slots', 'charging_status', 'city', 'id',
       'kind', 'geo_point', 'postal_code', 'public_name', 'rental_status',
       'slots', 'station_type', 'status', 'subscription_status', 'year',
       'month', 'day', 'hour', 'minute', 'usage_blue', 'usage_utilib',
       'usage_utilib14'],
      dtype='object')

In [148]:
df.head()

Address  Cars  bluecar_counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue Eugène Oudiné     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 24 columns]

Exporting the Cleaned Dataset

In [154]:
df1.to_csv('clean_data.csv')




In [155]:

df1= pd.read_csv('clean_data.csv', index_col=0, encoding='utf-8')
df1.head()

Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
3              51 Rue Eugène Oudiné     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2

[5 rows x 23 columns]

In [156]:
df1.shape

(2816, 23)

In [157]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2816 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Address              2816 non-null   object
 1   Cars                 2816 non-null   int64 
 2   Bluecar counter      2816 non-null   int64 
 3   Utilib counter       2816 non-null   int64 
 4   Utilib 1.4 counter   2816 non-null   int64 
 5   Charge Slots         2816 non-null   int64 
 6   Charging Status      2816 non-null   object
 7   City                 2816 non-null   object
 8   ID                   2816 non-null   object
 9   Kind                 2816 non-null   object
 10  Geo point            2816 non-null   object
 11  Postal code          2816 non-null   int64 
 12  Public name          2816 non-null   object
 13  Rental status        2816 non-null   object
 14  Slots                2816 non-null   int64 
 15  Station type         2816 non-null   object
 16  Status

DATA ANAYLISIS

In [165]:
#To compute usage, we will need to understand that we have to join successive (in time) 
#measures/counters for a given station, as the difference will tell whether a car was picked up, returned,
# or nothing happened.
#create a column  blue car counter usage

df['usage_blue'] = df.bluecar_counter.diff()

# creating column for utilib usage
df['usage_utilib'] = df.utilib_counter.diff()

# creating column for utilib 14 usage
df['usage_utilib14'] = df.utilib_14_counter.diff()

In [166]:
#positive number means that a car was returned \ negative number means that a car was picked\ 
#zero means that nothing happened
df.head()

address  cars  ...  usage_utilib  usage_utilib14
0                 2 Avenue de Suffren     0  ...           NaN             NaN
1           145 Rue Raymond Losserand     6  ...           0.0             0.0
2    2 Avenue John Fitzgerald Kennedy     3  ...           0.0             2.0
3              51 Rue Eugène Oudiné     3  ...           1.0            -2.0
4  6 avenue de la Porte de Champerret     3  ...          -1.0             0.0

[5 rows x 26 columns]

Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.

In [167]:
city_p = df[df['city'] == 'Paris']
pop_hour = city_p.groupby(['public_name', 'usage_blue' , 'hour'])[['bluecar_counter']].sum()
pop_hour.head()
#usage_blue is negetive meaning that the car was pick and most popular hour is 2100hrs


bluecar_counter
public_name           usage_blue hour                 
Paris/25 Août 1944/8 -5.0       21                  1
                      -4.0       18                  1
                      -3.0       18                  1
                       0.0       5                   0
                       1.0       20                  1

In [168]:

df[(df.city == 'Paris') & 
   (df.usage_blue < 0)].groupby('hour' ,)['usage_blue'].count().sort_values(ascending = False).head(1)


hour
21    80
Name: usage_blue, dtype: int64

What is the most popular hour for returning cars?

In [140]:

# usage_blue  is positive when returning the car 


df[(df.city == 'Paris') & 
   (df.usage_blue > 0)].groupby('hour')['usage_blue'].count().sort_values(ascending = False).head(1)


hour
3    49
Name: usage_blue, dtype: int64

What station is the most popular?

In [169]:

df[(df.kind == 'STATION') &  (df.status == 'ok')].groupby('public_name')[['kind']].count().sort_values(by = 'kind', ascending  = False).head(1)

kind
public_name                     
Paris/Porte de Montrouge/8    13

In [170]:
#At the most popular picking hour?
#What station is the most popular?
#Overall?
df[(df.kind == 'STATION') & (df.hour == 21)  & (df.status == 'ok')].groupby('public_name').count()[['kind']].sort_values(by = 'kind', ascending = False).head(1)

kind
public_name            
Paris/Tronchet/19     4

In [171]:
#What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?
#let first identify postal code is the most popular for picking up Blue cars
#we picking up car usage_blue is negetive 
df[df.usage_blue < 0].groupby('postal_code').count()[['usage_blue']].sort_values(by = 'usage_blue', ascending = False).head(1)

usage_blue
postal_code            
75015               116

In [172]:
#does the most popuar station belong to that postal code

df[df.public_name == 'Paris/Porte de Montrouge/8'][['public_name', 'postal_code']].head(1)

public_name  postal_code
122  Paris/Porte de Montrouge/8        75014

In [173]:
#At the most popular picking hour?
#when picking up the usage_bue is negetive
df[(df.usage_blue < 0) & (df.hour == 21)].groupby('postal_code').count()[['usage_blue']].sort_values(by = 'usage_blue', ascending = False).head(1)

usage_blue
postal_code            
75008                 9

Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars? 